import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import client from "../lib/sanity"
import Link from 'next/link'
import { useRouter } from 'next/router'
import PencilIcon from "@heroicons/react/solid/PencilIcon"
import DeleteIcon from "@heroicons/react/solid/TrashIcon"
import CloseIcon from "@heroicons/react/solid/XCircleIcon"
import Landing from '../components/LandingPage'

export async function getServerSideProps(context: any) {
  let users = await client.fetch('*[_type == "user"]{firstName, lastName, password, email, _id}')
  return {
    props: {
      users
    }
  }
}

const Home: NextPage = (props: any) => {
  const { users } = props
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing users={users} />
      </main >
    </div >
  )
}

export default Home
